import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import 'package:expense_wise/app/data/models/account.dart';
import 'package:expense_wise/app/data/models/transaction.dart';
import 'package:intl/intl.dart';

class PdfService {
  Future<void> generateAndShareReport(
    List<Account> accounts,
    List<Transaction> transactions,
  ) async {
    final pdf = pw.Document();
    final now = DateTime.now();
    final dateFormat = DateFormat('MMM d, yyyy');
    final currencyFormat = NumberFormat.simpleCurrency();

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(32),
        build: (context) {
          return [
            // Header
            pw.Header(
              level: 0,
              child: pw.Row(
                mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                children: [
                  pw.Text(
                    'ExpenseWise Report',
                    style: pw.TextStyle(
                      fontSize: 24,
                      fontWeight: pw.FontWeight.bold,
                    ),
                  ),
                  pw.Text(
                    dateFormat.format(now),
                    style: const pw.TextStyle(
                      fontSize: 14,
                      color: PdfColors.grey,
                    ),
                  ),
                ],
              ),
            ),
            pw.SizedBox(height: 20),

            // Accounts Summary
            pw.Text(
              'Account Summary',
              style: pw.TextStyle(fontSize: 18, fontWeight: pw.FontWeight.bold),
            ),
            pw.SizedBox(height: 10),
            pw.Table.fromTextArray(
              headers: ['Account', 'Type', 'Balance'],
              data: accounts.map((a) {
                return [
                  a.name,
                  a.type.name.toUpperCase(),
                  currencyFormat.format(a.balance),
                ];
              }).toList(),
              headerStyle: pw.TextStyle(fontWeight: pw.FontWeight.bold),
              cellAlignment: pw.Alignment.centerLeft,
            ),
            pw.SizedBox(height: 30),

            // Transactions
            pw.Text(
              'Recent Transactions',
              style: pw.TextStyle(fontSize: 18, fontWeight: pw.FontWeight.bold),
            ),
            pw.SizedBox(height: 10),
            pw.Table.fromTextArray(
              headers: ['Date', 'Category', 'Description', 'Amount'],
              data: transactions.take(100).map((t) {
                final isExpense = t.type == TransactionType.expense;
                final amountPrefix = isExpense ? '-' : '+';
                return [
                  dateFormat.format(t.date),
                  t.category.value?.name ?? 'Uncategorized',
                  t.note ?? '',
                  '$amountPrefix${currencyFormat.format(t.amount)}',
                ];
              }).toList(),
              headerStyle: pw.TextStyle(fontWeight: pw.FontWeight.bold),
              cellAlignment: pw.Alignment.centerLeft,
              cellAlignments: {
                3: pw.Alignment.centerRight, // Amount right aligned
              },
            ),

            pw.Footer(
              margin: const pw.EdgeInsets.only(top: 20),
              leading: pw.Text(
                'Generated by ExpenseWise',
                style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey),
              ),
            ),
          ];
        },
      ),
    );

    await Printing.sharePdf(
      bytes: await pdf.save(),
      filename: 'expense_wise_report_${DateFormat('yyyyMMdd').format(now)}.pdf',
    );
  }
}
